name: jacksi_ltd
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_preview: ^1.1.0
  dropdown_button2: 2.1.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_getit: ^1.2.1
  flutter_spinkit: ^5.2.0
  flutter_svg: null
  fluttertoast: ^8.2.2
  image: ^4.0.17
  image_picker: ^1.0.2
  path_provider: ^2.1.0
  shared_preferences: ^2.2.0
  sqflite: null

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/view_all.png
    - assets/images/category_one.png
    - assets/images/category_two.png
    - assets/images/category_three.png
    - assets/vectors/add.svg
    - assets/vectors/display_type.svg
    - assets/vectors/back.svg
    - assets/vectors/close.svg
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Arabic Black 900.otf
          weight: 900
        - asset: assets/fonts/Montserrat-Arabic ExtraBold 800.otf
          weight: 800
        - asset: assets/fonts/Montserrat-Arabic Bold 700.otf
          weight: 700
        - asset: assets/fonts/Montserrat-Arabic SemiBold 600.otf
          weight: 600
        - asset: assets/fonts/Montserrat-Arabic Medium 500.otf
          weight: 500
        - asset: assets/fonts/Montserrat-Arabic Regular 400.otf
          weight: 400
        - asset: assets/fonts/Montserrat-Arabic Light 300.otf
          weight: 300
